# fly.toml app configuration file generated for my-security-platform on 2025-08-18T14:19:42-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-security-platform'
primary_region = 'sjc'

[build]

[env]
  FLASK_ENV = 'production'
  PYTHONUNBUFFERED = '1'

[http_service]
  internal_port = 6991
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/'

[[vm]]
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 2048
