# fly.toml app configuration file for ExternalAttacker-MCP
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'externalattacker-complete'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile.complete'

[env]
  FLASK_ENV = 'production'
  PYTHONUNBUFFERED = '1'

[http_service]
  internal_port = 6991
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '15s'
    method = 'GET'
    path = '/'

[[vm]]
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 4096

# Increase disk space for security tools and scan results
[mounts]
  source = "scan_data"
  destination = "/app/scan_results"
  
[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static/"
